---
version: "3"
services:
  app:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-fpm
  app-fpm:
    build: .
    environment:
      DBHOST: db:3306
      DATABASE: training42
      DBUSER: duoquadra
      DBPASSWORD: crimson42
    depends_on:
      - db
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: crimson42
      MYSQL_DATABASE: training42
      MYSQL_USER: duoquadra
      MYSQL_PASSWORD: crimson42
    restart: always
    volumes:
      - ./sql/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql:ro
      - mariadb:/var/lib/mysql
volumes:
  mariadb: {}
...
